# Generated by Django 3.1.3 on 2021-01-24 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compound_name', models.CharField(max_length=100)),
                ('structure_url', models.CharField(blank=True, max_length=200, null=True)),
                ('iupac_name', models.CharField(max_length=200)),
                ('mobility', models.FloatField(blank=True, null=True)),
                ('skeletal_formula_file', models.CharField(blank=True, max_length=200, null=True)),
                ('experimental_data_file', models.CharField(max_length=200)),
                ('dft_data_file', models.CharField(blank=True, max_length=200, null=True)),
                ('dftb_data_file', models.CharField(blank=True, max_length=200, null=True)),
                ('chimes_data_file', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
